### ISSUE TITLE
Enhancement: Update Installation Documentation and Verify requirements.txt

### ISSUE THREAD

**Issue by azomDev** [LucianoXu/QRefine#5]
## Description

While attempting to install the project, I encountered multiple errors which suggest that the installation instructions may need updates for clarity and accuracy. Specifically, it would be helpful to include the required Python version and to verify if the `requirements.txt` file is up-to-date with all necessary dependencies.

## Suggested Enhancements

1. **Specify Python Version**: It would be beneficial for the installation section of the README to specify the exact version of Python required for this project. This information will help in setting up the right environment without running into compatibility issues.

2. **Verification of `requirements.txt`**: I faced several errors during the installation process that may be due to outdated or missing dependencies in `requirements.txt`. An example is tree_sitter which seems to be necessary for the working of the program.

I’m more than willing to assist in resolving these issues, whether it means providing logs, testing fixes, or any other support you might need. Thanks for looking into this!

Update: I tried the released zip version and it seems to be working without any errors for now, but I can see that the code in the `main` branch is way more advanced (graphical interface in the terminal for example), but what I describe above are the problems I get trying to install using the `main` branch.

**Comment by LucianoXu** [comment]
Thanks for your advice! I have updated the readme and requirements.txt accordingly, and tested on my server. It should work now.
By the way, may I ask where did you noticed our work?

**Comment by azomDev** [comment]
Hi, thanks for the quick response. I noticed your work as I am working as a research assistant working on exploring quantum correctness using specifications. I am reading the paper "Refinement calculus of quantum programs with projective
assertions" which lead me here. That paper was given to me by my research supervisor.

As for the program, I am still getting an error. Initially, I tried with python 3.12 which, if I remember correctly, removed support for `distutils` which was needed when installing the requirements. (It was fixable but there where more errors down the line).

I just tried with python version 3.11.9. I cloned the repository, I created an environement using `python -m venv env` and activated it using `.\env\Scripts\activate`. I am currently trying this on windows but I might try it later on linux if needed. Here are the logs of the command `pip install -r requirements.txt` when in the environement:

```
Collecting numpy==1.24.3 (from -r requirements.txt (line 1))
  Using cached numpy-1.24.3-cp311-cp311-win_amd64.whl.metadata (5.6 kB)
Collecting ply==3.11 (from -r requirements.txt (line 2))
  Using cached ply-3.11-py2.py3-none-any.whl.metadata (844 bytes)
Collecting rich==13.7.1 (from -r requirements.txt (line 3))
  Using cached rich-13.7.1-py3-none-any.whl.metadata (18 kB)
Collecting textual==0.55.0 (from -r requirements.txt (line 4))
  Using cached textual-0.55.0-py3-none-any.whl.metadata (5.6 kB)
Collecting tree-sitter==0.20.4 (from -r requirements.txt (line 5))
  Using cached tree_sitter-0.20.4-cp311-cp311-win_amd64.whl.metadata (7.5 kB)
Collecting tree-sitter-languages==1.10.2 (from -r requirements.txt (line 6))
  Using cached tree_sitter_languages-1.10.2-cp311-cp311-win_amd64.whl.metadata (11 kB)
Collecting markdown-it-py>=2.2.0 (from rich==13.7.1->-r requirements.txt (line 3))
  Using cached markdown_it_py-3.0.0-py3-none-any.whl.metadata (6.9 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich==13.7.1->-r requirements.txt (line 3))
  Using cached pygments-2.18.0-py3-none-any.whl.metadata (2.5 kB)
Collecting typing-extensions<5.0.0,>=4.4.0 (from textual==0.55.0->-r requirements.txt (line 4))
  Using cached typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich==13.7.1->-r requirements.txt (line 3))
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Collecting linkify-it-py<3,>=1 (from markdown-it-py[linkify,plugins]>=2.1.0->textual==0.55.0->-r requirements.txt (line 4))
  Using cached linkify_it_py-2.0.3-py3-none-any.whl.metadata (8.5 kB)
Collecting mdit-py-plugins (from markdown-it-py[linkify,plugins]>=2.1.0->textual==0.55.0->-r requirements.txt (line 4))
  Using cached mdit_py_plugins-0.4.1-py3-none-any.whl.metadata (2.8 kB)
Collecting uc-micro-py (from linkify-it-py<3,>=1->markdown-it-py[linkify,plugins]>=2.1.0->textual==0.55.0->-r requirements.txt (line 4))
  Using cached uc_micro_py-1.0.3-py3-none-any.whl.metadata (2.0 kB)
Using cached numpy-1.24.3-cp311-cp311-win_amd64.whl (14.8 MB)
Using cached ply-3.11-py2.py3-none-any.whl (49 kB)
Using cached rich-13.7.1-py3-none-any.whl (240 kB)
Using cached textual-0.55.0-py3-none-any.whl (547 kB)
Using cached tree_sitter-0.20.4-cp311-cp311-win_amd64.whl (107 kB)
Using cached tree_sitter_languages-1.10.2-cp311-cp311-win_amd64.whl (8.3 MB)
Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Using cached linkify_it_py-2.0.3-py3-none-any.whl (19 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached mdit_py_plugins-0.4.1-py3-none-any.whl (54 kB)
Using cached uc_micro_py-1.0.3-py3-none-any.whl (6.2 kB)
Installing collected packages: ply, uc-micro-py, typing-extensions, tree-sitter, pygments, numpy, mdurl, tree-sitter-languages, markdown-it-py, linkify-it-py, rich, mdit-py-plugins, textual
Successfully installed linkify-it-py-2.0.3 markdown-it-py-3.0.0 mdit-py-plugins-0.4.1 mdurl-0.1.2 numpy-1.24.3 ply-3.11 pygments-2.18.0 rich-13.7.1 textual-0.55.0 tree-sitter-0.20.4 tree-sitter-languages-1.10.2 typing-extensions-4.12.2 uc-micro-py-1.0.3
```


This seems to be fine (with python 3.12 there were errors here)

Just after, when I run `python boot.py`, I get this:

```
Generating LALR tables
WARNING: 100 shift/reduce conflicts
WARNING: 86 reduce/reduce conflicts
WARNING: reduce/reduce conflict in state 20 resolved using rule (term -> var)
WARNING: rejected rule (statement -> var) in state 20
WARNING: reduce/reduce conflict in state 79 resolved using rule (term -> statement)
WARNING: rejected rule (statement -> statement statement) in state 79
WARNING: reduce/reduce conflict in state 81 resolved using rule (term -> var)
WARNING: rejected rule (statement -> var) in state 81
WARNING: reduce/reduce conflict in state 88 resolved using rule (term -> statement)
WARNING: rejected rule (statement -> EXTRACT statement) in state 88
WARNING: reduce/reduce conflict in state 122 resolved using rule (term -> statement)
WARNING: rejected rule (statement -> statement LEQ statement) in state 122
Traceback (most recent call last):
  File "C:\Users\myName\Desktop\Rem\boot.py", line 3, in <module>
    from rem import app_run, predefined
  File "C:\Users\myName\Desktop\Rem\rem\__init__.py", line 1, in <module>
    from .app import app_run
  File "C:\Users\myName\Desktop\Rem\rem\app\__init__.py", line 1, in <module>
    from .app import app_run
  File "C:\Users\myName\Desktop\Rem\rem\app\app.py", line 6, in <module>
    from .editor import Editor
  File "C:\Users\myName\Desktop\Rem\rem\app\editor.py", line 19, in <module>
    from ..qrefine.prover.gen.gen_machine import GenMachine
  File "C:\Users\myName\Desktop\Rem\rem\qrefine\prover\gen\gen_machine.py", line 54, in <module>
    class GenMachine:
  File "C:\Users\myName\Desktop\Rem\rem\qrefine\prover\gen\gen_machine.py", line 56, in GenMachine
    mp.set_start_method('fork')
  File "C:\Python311\Lib\multiprocessing\context.py", line 251, in set_start_method
    self._actual_context = self.get_context(method)
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\context.py", line 243, in get_context
    return super().get_context(method)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\multiprocessing\context.py", line 193, in get_context
    raise ValueError('cannot find context for %r' % method) from None
ValueError: cannot find context for 'fork'
```

My thoughts is that it might be a problem with my python version (3.11.9 is the latest 3.11 version on the official website) or mabye somehow with the environment since I am not using conda. If there is anything else I can provide to help, please let me know.


EDIT: I tried with linux and with the same things as when I tried with windows, it now appear to be working without errors. I am able to go to the editor without the program crashing. I will test a bit the working version on linux in the next few days. I will as well try a few more things on windows to see if I can get it working.

**Comment by LucianoXu** [comment]
Hi Azom, Rew was developed on MacOS and tested on Linux. There are some issues on Windows, and I have fixed them:
- multiprocessing, there are platform specific configurations, and
- tree-sitter, the syntax highlighting requires some wasm modules, which I am not so familiar with.
Therefore I disabled syntax highlighting on Windows, and it should be working now. See the latest commit on the main branch.

Also, I uploaded the tutorial video we submitted together with the draft paper, and you can find it in the README. I am glad to help if you have further questions on the implementation or the topic.
